#!/bin/bash

# compton --config ~/.compton.conf -b
compton --config /dev/null --backend glx --vsync opengl-swc -b

# conky | while read -r; do xsetroot -name "$REPLY"; done &

killall dwm-status > /dev/null 2>& 1
dwm-status 3 &
dwm-start wallpaper
